{{- define "gitHubRepoArchive" }}
  {{- $url := printf "https://github.com/%s/archive/master.zip" .repo }}
  {{- if (get . "latest") }}
  {{- $url = printf "https://github.com/%s/archive/%s.zip" .repo (trim (gitHubLatestRelease .repo).TagName) }}
  {{- else if (get . "branch") }}
  {{- $url = printf "https://github.com/%s/archive/%s.zip" .repo .branch }}
  {{- end }}
  type: archive
  url: {{ $url }}
  exact: true
  stripComponents: 1
  refreshPeriod: 168h
{{- end -}}

{{- if not (eq (index .chezmoi.args 1) "execute-template") -}}

# Oh-my-zsh
{{ .ohMyZshDir }}:
  {{- template "gitHubRepoArchive" .ohMyZsh }}

# Oh-my-zsh themes
{{ range .ohMyZshThemes -}}
  {{- $.ohMyZshThemesDir -}}/{{ base .repo }}:
  {{- template "gitHubRepoArchive" . }}
{{ end }}

# Oh-my-zsh plugins
{{ range .ohMyZshPlugins -}}
  {{- $.ohMyZshPluginsDir -}}/{{ base .repo }}:
  {{- template "gitHubRepoArchive" . }}
{{ end }}

# Oh-my-tmux
{{ .ohMyTmuxDir }}:
  {{- template "gitHubRepoArchive" .ohMyTmux }}

# Ranger plugins
{{ range .rangerPlugins -}}
  {{- $.rangerPluginsDir -}}/{{ base .repo | snakecase }}:
  {{- template "gitHubRepoArchive" . }}
{{ end }}

# Vim-plug
.local/share/nvim/site/autoload/plug.vim:
  type: "file"
  url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
  refreshPeriod: "168h"
.vim/autoload/plug.vim:
  type: "file"
  url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
  refreshPeriod: "168h"

{{- end }}
