externalSource:
  ohMyZshDir: .config/oh-my-zsh
  ohMyZsh:
    repo: ohmyzsh/ohmyzsh

  ohMyZshThemesDir: .config/oh-my-zsh/custom/themes
  ohMyZshThemes:
    - repo: romkatv/powerlevel10k
      latest: true

  ohMyZshPluginsDir: .config/oh-my-zsh/custom/plugins
  ohMyZshPlugins:
    - repo: zsh-users/zsh-syntax-highlighting
    - repo: zsh-users/zsh-autosuggestions
    - repo: zsh-users/zsh-completions
    - repo: MuXiu1997/zsh-vi-mode
      branch: main
    - repo: Aloxaf/fzf-tab

  ohMyTmuxDir: .config/oh-my-tmux
  ohMyTmux:
    repo: MuXiu1997/.tmux
    branch: main

  rangerPluginsDir: .config/ranger/plugins
  rangerPlugins:
    - repo: alexanderjeurissen/ranger_devicons
      branch: main
    - repo: MuXiu1997/ranger-yoink
      branch: main
    - repo: MuXiu1997/ranger-airdrop
      branch: main
    - repo: MuXiu1997/ranger-fzf-filter
      branch: main
    - repo: jchook/ranger-zoxide

  hammerspoonDir: .config/hammerspoon
  hammerspoon:
    repo: MuXiu1997/hammerspoon
    branch: main

XDG:
  remove:
    # zsh
    - .zshrc
    - .zprofile
    - .zsh_history
    - .zsh_sessions
    - .zcompdump
    # tmux
    - .tmux.conf
    # git
    - .gitconfig
    # fzf
    - .fzf.zsh
    # wget
    - .wgetrc
    - .wget-hsts
    # nvm
    - .nvm
    # npm
    - .npm
    - .npmrc
    # pnpm
    - .pnpm-state
    - .pnpm-store
    # pyenv
    - .pyenv
    # go
    - go
    # gradle
    - .gradle
    # maven
    - .m2
    # hammerspoon
    - .hammerspoon

