{{- define "gitHubRepoArchive" }}
  {{- $name := "master" }}
  {{- if (get . "latest") }}
  {{- $name = trim (gitHubLatestRelease .repo).TagName }}
  {{- else if (get . "branch") }}
  {{- $name = .branch }}
  {{- end }}
  type: archive
  url: {{ printf "https://github.com/%s/archive/%s.zip" .repo $name }}
  exact: true
  stripComponents: 1
  refreshPeriod: 168h
{{- end -}}

{{- if not (eq (index .chezmoi.args 1) "execute-template") -}}
{{- with .externalSource -}}
{{- $es := . -}}

# Oh-my-zsh
{{ .ohMyZshDir }}:
  {{- template "gitHubRepoArchive" .ohMyZsh }}

# Oh-my-zsh themes
{{ range .ohMyZshThemes -}}
  {{- $es.ohMyZshThemesDir -}}/{{ base .repo }}:
  {{- template "gitHubRepoArchive" . }}
{{ end }}

# Oh-my-zsh plugins
{{ range .ohMyZshPlugins -}}
  {{- $es.ohMyZshPluginsDir -}}/{{ base .repo }}:
  {{- template "gitHubRepoArchive" . }}
{{ end }}

# Oh-my-tmux
{{ .ohMyTmuxDir }}:
  {{- template "gitHubRepoArchive" .ohMyTmux }}

# Ranger plugins
{{ range .rangerPlugins -}}
  {{- $es.rangerPluginsDir -}}/{{ base .repo | snakecase }}:
  {{- template "gitHubRepoArchive" . }}
{{ end }}

# Hammerspoon
{{ .hammerspoonDir }}:
  {{- template "gitHubRepoArchive" .hammerspoon }}

# Nvim
.config/nvim:
  type: archive
  url: https://github.com/MuXiu1997/nvim/releases/download/{{ (gitHubLatestRelease "MuXiu1997/nvim").TagName }}/nvim.zip
  exact: true
  refreshPeriod: 168h

# Completion
{{ if lookPath "docker" -}}
.local/share/zsh/site-functions/_docker:
  type: file
  url: https://raw.githubusercontent.com/docker/cli/v{{ regexFind "\\d+\\.\\d+\\.\\d+" (output "docker" "--version") }}/contrib/completion/zsh/_docker
  refreshPeriod: 168h
{{- end }}
{{ if lookPath "docker-compose" -}}
.local/share/zsh/site-functions/_docker-compose:
  type: file
  url: https://raw.githubusercontent.com/docker/compose/{{ regexFind "\\d+\\.\\d+\\.\\d+" (output "docker-compose" "--version") }}/contrib/completion/zsh/_docker-compose
  refreshPeriod: 168h
{{- end }}
.local/share/zsh/site-functions/_nvm:
  type: file
  url: https://github.com/zsh-users/zsh-completions/raw/master/src/_nvm
  refreshPeriod: 168h

{{- end }}
{{- end }}
