.oh-my-zsh:
  type: "archive"
  url: "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
  exact: true
  stripComponents: 1
  refreshPeriod: "168h"

.oh-my-tmux:
  type: "archive"
  url: "https://github.com/gpakosz/.tmux/archive/master.tar.gz"
  exact: true
  stripComponents: 1
  refreshPeriod: "168h"

# Oh-my-zsh themes
.oh-my-zsh/custom/themes/powerlevel10k:
  type: "archive"
  url: "https://github.com/romkatv/powerlevel10k/archive/master.tar.gz"
  exact: true
  stripComponents: 1
  refreshPeriod: "168h"

# Oh-my-zsh plugins
.oh-my-zsh/custom/plugins/zsh-syntax-highlighting:
  type: "archive"
  url: "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
  exact: true
  stripComponents: 1
  refreshPeriod: "168h"
.oh-my-zsh/custom/plugins/zsh-autosuggestions:
  type: "archive"
  url: "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
  exact: true
  stripComponents: 1
  refreshPeriod: "168h"
.oh-my-zsh/custom/plugins/zsh-completions:
  type: "archive"
  url: "https://github.com/zsh-users/zsh-completions/archive/master.tar.gz"
  exact: true
  stripComponents: 1
  refreshPeriod: "168h"
.oh-my-zsh/custom/plugins/zsh-vi-mode:
  type: "archive"
  url: "https://github.com/jeffreytse/zsh-vi-mode/archive/master.tar.gz"
  exact: true
  stripComponents: 1
  refreshPeriod: "168h"
.oh-my-zsh/custom/plugins/ranger-zoxide:
  type: "archive"
  url: "https://github.com/MuXiu1997/ranger-zoxide/archive/main.tar.gz"
  exact: true
  stripComponents: 1
  refreshPeriod: "168h"
.oh-my-zsh/custom/plugins/fzf-tab:
  type: "archive"
  url: "https://github.com/Aloxaf/fzf-tab/archive/master.tar.gz"
  exact: true
  stripComponents: 1
  refreshPeriod: "168h"
.oh-my-zsh/custom/plugins/forgit:
  type: "archive"
  url: "https://github.com/wfxr/forgit/archive/master.tar.gz"
  exact: true
  stripComponents: 1
  refreshPeriod: "168h"

# Ranger plugins
.config/ranger/plugins/ranger_devicons:
  type: "archive"
  url: "https://github.com/alexanderjeurissen/ranger_devicons/archive/main.tar.gz"
  exact: true
  stripComponents: 1
  refreshPeriod: "168h"
.config/ranger/plugins/ranger_yoink:
  type: "archive"
  url: "https://github.com/MuXiu1997/ranger-yoink/archive/main.tar.gz"
  exact: true
  stripComponents: 1
  refreshPeriod: "168h"
.config/ranger/plugins/ranger_airdrop:
  type: "archive"
  url: "https://github.com/MuXiu1997/ranger-airdrop/archive/main.tar.gz"
  exact: true
  stripComponents: 1
  refreshPeriod: "168h"
.config/ranger/plugins/ranger_fzf_filter:
  type: "archive"
  url: "https://github.com/MuXiu1997/ranger-fzf-filter/archive/main.tar.gz"
  exact: true
  stripComponents: 1
  refreshPeriod: "168h"

# Vim-plug
.local/share/nvim/site/autoload/plug.vim:
  type: "file"
  url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
  refreshPeriod: "168h"
.vim/autoload/plug.vim:
  type: "file"
  url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
  refreshPeriod: "168h"
