tap "homebrew/bundle"
tap "homebrew/cask", "https://github.com/Homebrew/homebrew-cask.git"
tap "homebrew/cask-fonts", "https://github.com/Homebrew/homebrew-cask-fonts.git"
tap "homebrew/core", "https://github.com/Homebrew/homebrew-core.git"
tap "hpedrorodrigues/tools"
tap "vldmrkl/formulae"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Secure and free password manager for all of your devices
brew "bitwarden-cli"
# Collection of portable C++ source libraries
brew "boost"
# Yet another cross-platform graphical process/system monitor
brew "bottom"
# Manage your dotfiles across multiple diverse machines, securely
brew "chezmoi"
# Top-like interface for container metrics
brew "ctop"
# Load/unload environment variables based on $PWD
brew "direnv"
# Tool for managing dock items
brew "dockutil"
# More intuitive version of du in rust
brew "dust"
# Modern replacement for 'ls'
brew "exa"
# Simple, fast and user-friendly alternative to find
brew "fd"
# macOS CLI for managing custom icons for files and folders
brew "fileicon"
# Collection of reusable C++ library artifacts developed at Facebook
brew "folly"
# Terminal JSON viewer
brew "fx"
# Command-line fuzzy finder written in Go
brew "fzf"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Syntax-highlighting pager for git and diff output
brew "git-delta"
# Library for command-line editing
brew "readline"
# GNU Ubiquitous Intelligent Language for Extensions
brew "guile"
# Validating, recursive, caching DNS resolver
brew "unbound"
# GNU Transport Layer Security (TLS) Library
brew "gnutls"
# GNU Pretty Good Privacy (PGP) package
brew "gnupg"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Go implementation of configuration language for defining JSON data
brew "go-jsonnet"
# Go version management
brew "goenv", args: ["HEAD"]
# Fast linters runner for Go
brew "golangci-lint"
# GO Simple Tunnel - a simple tunnel written in golang
brew "gost"
# Command-line tool for generating regular expressions
brew "grex"
# Like cURL, but for gRPC
brew "grpcurl"
# System monitoring dashboard for terminal
brew "gtop"
# Manage your Java environment
brew "jenv"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Lazier way to manage everything docker
brew "lazydocker"
# Simple terminal UI for git commands
brew "lazygit"
# Clone of ls with colorful output, file type icons, and more
brew "lsd"
# Powerful, lightweight programming language
brew "lua"
# Bare libuv bindings for lua
brew "luv"
# Utility for directing compilation
brew "make"
# Mac App Store command-line interface
brew "mas"
# Development kit for the Java programming language
brew "openjdk"
# Java-based project management
brew "maven"
# Fast, highly customisable system info script
brew "neofetch"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# HTTP/2 C Library
brew "nghttp2"
# Manage multiple Node.js versions
brew "nvm"
# Development kit for the Java programming language
brew "openjdk@11"
# Interpreted, interactive, object-oriented programming language
brew "python@3.10"
# Python package management tool
brew "poetry"
# Protocol buffers (Google's data interchange format)
brew "protobuf"
# Python version management
brew "pyenv"
# Interpreted, interactive, object-oriented programming language
brew "python@3.9"
# File browser
brew "ranger"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Utility that provides fast incremental file transfer
brew "rsync"
# Powerful, clean, object-oriented scripting language
brew "ruby"
# 7-Zip is a file archiver with a high compression ratio
brew "sevenzip"
# Simplified and community-driven man pages
brew "tldr"
# Terminal multiplexer
brew "tmux"
# Program that allows you to count code, quickly
brew "tokei"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Vi 'workalike' with many additional features
brew "vim"
# Internet file retriever
brew "wget"
# XML command-line utilities
brew "xmlstarlet"
# Process YAML documents from the CLI
brew "yq"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# macOS CLI for AirDrop
brew "vldmrkl/formulae/airdrop-cli"
# Application launcher and productivity software
cask "alfred"
# Redis desktop manager
cask "another-redis-desktop-manager"
# Desktop password and login vault
cask "bitwarden"
# Translation application for text, pictures, and manual input
cask "bob"
# Server and cloud storage browser
cask "cyberduck"
# Teamwork app by Alibaba Group
cask "dingtalk"
# Command-line utility for managing macOS dock items
cask "dockutil"
# Downloads videos from different websites
cask "downie"
# Terminal/ssh/sftp client
cask "electerm"
# Download accelerator and organizer
cask "free-download-manager"
# Tools to protect your files
cask "gpg-suite-no-mail"
# Utility to hide menu bar items
cask "hiddenbar"
# Free and open-source media player
cask "iina"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# JetBrains tools manager
cask "jetbrains-toolbox"
# Open-source screen recorder built with web technology
cask "kap"
# Open-source keystroke visualizer
cask "keycastr"
# Snippet management app
cask "lepton"
# Utility to open, create and modify archive files
cask "maczip"
# Provides updates to various Microsoft products
cask "microsoft-auto-update"
# Web browser
cask "microsoft-edge"
# Smooths scrolling and set mouse scroll directions independently
cask "mos"
# Re-mounts write-protected NTFS volumes
cask "mounty"
# Neovim Client
cask "neovide"
# Music streaming platform
cask "neteasemusic"
# Collaboration platform for API development
cask "postman"
# QuickLook plug-in that renders source code with syntax highlighting
cask "qlcolorcode"
# QuickLook generator for Markdown files
cask "qlmarkdown"
cask "qlstephen"
# Instant messaging tool
cask "qq"
cask "quicklook-json"
# Move and resize windows using keyboard shortcuts or snap areas
cask "rectangle"
# Displays all open files and sockets in use by all running processes
cask "sloth"
# Snip or pin screenshots
cask "snipaste"
# Rime input method engine
cask "squirrel"
# System monitor for the menu bar
cask "stats"
# App to switch hosts
cask "switchhosts"
# Configurable document editor that supports Markdown
cask "typora"
# Free messaging and calling application
cask "wechat"
# Wechat DevTools for Official Account and Mini Program development
cask "wechatwebdevtools"
mas "Spark", id: 1176895641
mas "WPS Office", id: 1443749478
mas "Xcode", id: 497799835