# $schema: https://github.com/jesseduffield/lazygit/raw/master/schema/config.json

gui:
  nerdFontsVersion: '3'
  timeFormat: '2006-01-02'
  shortTimeFormat: '15:04:05'
  sidePanelWidth: 0.2
  authorColors:
    'MuXiu1997': '#B8AFE6'
git:
  paging:
    colorArg: always
    pager: >
      delta
      --features lazygit
      --max-line-length {{columnWidth}}
      -s
  parseEmoji: true

customCommands:
  - key: T
    description: '[ tag ]'
    command: '$(dirname ${LG_CONFIG_FILE})/scripts/tag "{{ .SelectedLocalCommit.Sha }}"'
    context: commits
    subprocess: true
  - key: n
    description: '[ new remote ]'
    command: '$(dirname ${LG_CONFIG_FILE})/scripts/new-remote'
    context: remotes
    subprocess: true
  - key: P
    description: '[ push tag ]'
    command: '$(dirname ${LG_CONFIG_FILE})/scripts/push-tag "{{ .SelectedTag.Name }}"'
    context: tags
    subprocess: true
  - key: N
    description: '[ push branch ]'
    command: '$(dirname ${LG_CONFIG_FILE})/scripts/custom-push --local-branch "{{ .SelectedLocalBranch.Name }}"'
    context: localBranches
    subprocess: true
  - key: N
    description: '[ push commit ]'
    command: '$(dirname ${LG_CONFIG_FILE})/scripts/custom-push --commit "{{ .SelectedLocalCommit.Sha }}"'
    context: commits
    subprocess: true
