name: Mirror Github to Gitee
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'
jobs:
  run:
    name: Sync GitHub to Gitee
    runs-on: ubuntu-latest
    steps:
    - name: dotfiles repo mirror.
      uses: Yikun/hub-mirror-action@master
      with:
        src: github/MuXiu1997
        dst: gitee/MuXiu1997
        static_list: 'dotfiles'
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        force_update: true

